database/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    re_path(r'^delete/(?P<delete_id>[0-9]+$)', views.delete, name='delete'),
    re_path(r'^images/(?P<slugInput>[\w-]+$)', views.images2, name='images2'),
    re_path(r'^update/(?P<update_id>[0-9]+$)', views.update, name='update'),
    re_path(r'^add$', views.add, name='add'),
    re_path(r'^$', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mywebsite/urls.py
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

from database.views import predictImage

from .views import index, Login, Logout, Registration

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^database/', include(('database.urls', 'database'), namespace='database')),
    re_path(r'^predictImage$', predictImage, name='predictImage'),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    re_path(r'^Registration', Registration, name='registration'),
    re_path(r'^Logout$', Logout, name='logout'),
    re_path(r'^Login$', Login, name='login'),
    re_path(r'^$', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

database/models.py
from datetime import datetime
from unicodedata import name
from django.db import models
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.utils import timezone, formats
import pytz

    # indonesia_tz = pytz.timezone('Asia/Jakarta')
    # time = timezone.localtime(waktu_update)
    # time.strftime("%d %B %Y %H:%M:%S")
class PostModel(models.Model):
    id = models.BigAutoField(primary_key=True)
    gambar = models.ImageField(upload_to='', null = True, blank = False)
    waktu = models.DateTimeField(auto_now_add=True)
    waktu_update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)

    def waktu_indonesia(self):
        waktu_indo = timezone.localtime(self.waktu, pytz.timezone('Asia/Jakarta'))
        return waktu_indo.strftime("%d %B %Y %H:%M WIB")
    
    def waktu_update_indonesia(self):
        waktu_update_indo = timezone.localtime(self.waktu_update, pytz.timezone('Asia/Jakarta'))
        return waktu_update_indo.strftime("%d %B %Y %H:%M WIB")
    
    LIST_CATEGORY = (
        ('Pneumonia', 'Pneumonia'),
        ('Tuberculosis', 'Tuberculosis'),
        ('COVID19', 'COVID19'),
        ('Normal', 'Normal'),
    )

    category = models.CharField(
        max_length=100,
        choices=LIST_CATEGORY,blank=False
    )

    def save(self):
        self.slug = slugify(self.gambar)
        super(PostModel, self).save()

    def __str__(self):
        return "{}. {}".format(self.id, self.gambar)

database/forms.py
from django import forms

from .models import PostModel

#class PostForm(forms.Form):
   #nama = forms.CharField(max_length=255)
   #keterangan = forms.CharField()
   #gambar = forms.ImageField()
   
class PostForm(forms.ModelForm):
   class Meta:
      model = PostModel
      fields = [
         'gambar',
         'category',
      ]

      labels={
         'gambar':'Image :',
         'category':'Category :',
      }

      # widget={
      #    'id_gambar' : forms.FileInput(
      #       attrs={
      #          'class':'form-control'}
      #    ),

      #    'id_category' : forms.Select(
      #       attrs={
      #          'class':'form-select'}
      #    ),
      # }
         
      

database/views.py
from random import choice
from django.shortcuts import redirect, render
from django.views import View
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import os
from PIL import Image

from keras.models import load_model
from keras_preprocessing import image
import tensorflow as tf
import numpy as np

from mywebsite.forms import MainForm

from .models import PostModel
from .forms import PostForm

from keras.utils import to_categorical



model_graph = tf.compat.v1.Graph()
with model_graph.as_default():
    tf_session = tf.compat.v1.Session()
    with tf_session.as_default():
        model = load_model('models/model_hybrid3.h5')

def delete(request, delete_id):
    PostModel.objects.filter(id=delete_id).delete()
    return redirect('database:index')

def update(request, update_id):
    image_update = PostModel.objects.filter(id=update_id).first()
    post_model = PostModel.objects.all()

    data={
        'category'  : image_update.category,
        'gambar'  : image_update.gambar,
    }
    post_form = PostForm(request.POST or None, request.FILES or None, initial=data, instance=image_update)

    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()

        return redirect('database:index')    
    
    # post_model = [image_update] + list(post_model.exclude(id=update_id))

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        'Post_Form':post_form,
    }
    return render(request, 'database/update.html', context)

def images2(request, slugInput):
    #query
    post_model = PostModel.objects.filter(slug=slugInput).first()
    print("cekkkkkkkkkkkkkkkkk")
    print(post_model)

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':post_model,
        # 'Post_Form':post_form,
    }
    return render(request, 'database/images2.html', context)

def add(request):
    post_form = PostForm(request.POST, request.FILES)

    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()

        return redirect('database:index')    

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Form':post_form,

        
    }
    return render(request, 'database/add.html', context)


def predictImage(request):
    if request.method == 'POST':
        main_form = MainForm(request.POST, request.FILES)
        if main_form.is_valid():

            simpan=request.FILES['gambar']
            fs=FileSystemStorage()
            Path_Gambar=fs.save(simpan.name,simpan)
            Path_Gambar=fs.url(Path_Gambar)


            testimage = 'database/images/' + Path_Gambar
            img = image.load_img(testimage, target_size=(224,224))
            xray_image = image.img_to_array(img)
            xray_image=xray_image/225
            xray_image=xray_image.reshape(1,224,224,3)
            with model_graph.as_default():
                with tf_session.as_default():
                    prediksi = model.predict(xray_image)

            hasil=int(np.argmax(prediksi,axis=1))
            probability = max(prediksi.tolist()[0])
            probability = round(probability*100,2)
            probability = str(probability) + '%'

            # menentukan kategori dari hasil prediksi
            if hasil==0:
                category='COVID19'
            elif hasil==1:
                category='Normal'
            elif hasil==2:
                category='Tuberculosis'
            elif hasil==3:
                category='Pneumonia'
                
            # simpan gambar dan kategori ke dalam model PostModel
            post_model = PostModel(category=category, gambar=Path_Gambar)
            post_model.save()

            # menghitung akurasi
            # hasil = to_categorical(hasil, num_classes=4)
            # model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
            # scores = model.evaluate(xray_image, np.array([hasil]))
            # accuracy = round(scores[1]*100, 2)

    template_name=None
    if request.user.is_authenticated:
        template_name= 'index_user.html'
    else:
        template_name= 'index_anonymous.html'

    context = {
            'Top' : 'Lung Disease Website',
            'Judul': 'Lung Disease Detection ',
            'Subjudul' : 'Main Page',
            'Main_Form' : main_form,
            'Path_Gambar':Path_Gambar,
            'Hasil':category,
            'probability':probability,
            # 'accuracy':accuracy,
            'hideLoading': True,
            #'Main_model':main_model,
           
            'nav': [
                ['/','home'],
                ['/database','database']
            ],
            
        }
    return render(request, template_name, context)

@login_required(login_url='login')
def index(request):
    #query
    post_model = PostModel.objects.order_by('-waktu_update')
    page = request.GET.get('page', 1)
    paginator = Paginator(post_model, 10)

    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)


    post_form = PostForm(request.POST, request.FILES)

    template_name=None
    if request.user.is_authenticated:
        template_name= 'database/index_user.html'
    else:
        template_name= 'database/index_anonymous.html'
    

    context = {
        "Judul" : "Database of Lung Disease Detection",
        "Subjudul" : "Database Page",
        'nav': [
            ['/','home'],
            ['/database','database']
        ],
        'Post_Model':users,
        'Post_Form':post_form,

        
    }
    return render(request, template_name, context)




            # p = PostModel(category="COVID19", gambar=Path_Gambar)
            # q = PostModel(category='Normal', gambar=Path_Gambar)
            # r = PostModel(category='Tuberculosis', gambar=Path_Gambar)
            # s = PostModel(category='Pneumonia', gambar=Path_Gambar)
            
            # if hasil==0:
            #     hasil=p.category
            #     p.save()
            # elif hasil==1:
            #     hasil=q.category
            #     q.save()
            # elif hasil==2:
            #     hasil=r.category
            #     r.save()
            # elif hasil==3:
            #     hasil=s.category
            #     s.save()


# def images(request, slugInput):
#     #query
#     post_model = PostModel.objects.filter(slug=slugInput).first()
#     print("cekkkkkkkkkkkkkkkkk")
#     print(post_model)

#     context = {
#         "Judul" : "Database of Lung Disease Detection",
#         "Subjudul" : "Database Page",
#         'nav': [
#             ['/','home'],
#             ['/database','database']
#         ],
#         'Post_Model':post_model,
#         # 'Post_Form':post_form,
#     }
#     return render(request, 'database/images.html', context)

    # if request.method == 'POST':
    #     if post_form.is_valid():
    #         post_form.save()

    #     #     simpan = request.FILES['gambar']
    #     #     fss=FileSystemStorage()
    #     #     Path_Gambar=fss.save(simpan.name,simpan)
    #     #     Path_Gambar2=fss.url(Path_Gambar)

    #     # else:
    #     #     post_model

    #     return redirect('database:index')    

database/templates/database/add.html
{% extends "html_user/base_user.html"%}
{% load static %}
{% load tz %}
{% load widget_tweaks%}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styless.css" %}">
{% endblock app_css%} 

{% block base%}
<section class="jumbotron jumbotron-fluid text-black text-center" style="margin-top: 3rem; padding-bottom: 0rem;">
    <h1 class="display-4 ">{{ Judul }}</h1>
</section>

<section class="container-fluid glass" style="margin-top: -6rem">
    <h3 class="text-center" style="margin: 2rem;">Add the Database</h3>
        <div class="data-form ">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupSelect01">{% render_field Post_Form.category.label %}</label>
                    {% render_field Post_Form.category class="form-control" id="inputGroupSelect01"%}
                </div>
                <br>
                <div class="input-group mb-3">
                    {% render_field Post_Form.gambar class="form-control" id="inputGroupFile02" type="file"%}
                    <button class="btn btn-outline-secondary" type="submit">Upload</button>
                </div>    
                
            </form>
        </div>
    </div>
</section>
{% endblock base%}

database/templates/database/images2.html
{% extends "html_user/base_user.html"%}
{% load static %}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styless.css" %}">
{% endblock app_css%} 

{% block base%}
<section class="jumbotron jumbotron-fluid text-black text-center" style="margin-top: 3rem; padding-bottom: 0rem;">
    <h1 class="display-4 ">{{ Judul }}</h1>
</section>

<section class="container-fluid glass" style="margin-top: -6rem">
    <div class="data-form">
        <br>
        <h2 class="text-center">Result of Lung Disease Detection Data</h2>
        <h5>
            <figure class="text-center" style="margin-top: 20px;">
                <img src="{{Post_Model.gambar}}" class="img-fluid img-thumbnail" alt="">
            </figure>
        </h5>
        <h6>
            <div class="text-center">
                <h3>Result : {{Post_Model.category}}</h3>
                <br>
                <!-- <h3>Probability : {{probability}}</h3> -->
            </div>
        </h6>
</div>
</section>
{% endblock base%}

database/templates/database/index_user.html
{% extends "html_user/base_user.html"%}
{% load static %}
{% load tz %}
{% load widget_tweaks%}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styless.css" %}">
{% endblock app_css%} 

{% block base%}
<section class="jumbotron jumbotron-fluid text-black text-center" style="margin-top: 3rem; margin-bottom: -5rem;">
    <h1 class="display-4 ">{{ Judul }}</h1>
</section>


<div class="container bg-white text-dark shadow" style="margin-bottom: 70px; min-height: 40rem;">
    <div style="height: auto;">
        <br>
        <div class="container" style="padding-bottom: 27px;">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <b>List of X-ray Thorax Images</b>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'database:add' %}" class="btn btn-success" style="margin-bottom: 4px;
                            margin-top: -19px;">Add</a>
                            <table class = "table" >
                                <thead class = "thead-light">
                                    <tr>
                                        <th widht="3%">No.</th>
                                        <th width="37%">Result</th>
                                        <th width="20%">File</th>
                                        <th></th>
                                        <th width="20%">Time</th>
                                        <th width="15%">Update</th>
                                        <th width="15%">Delete</th>
                                    </tr>
                                </thead>
                                <tbody >
                                    {% for post in Post_Model%}
                                    <tr >
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td>{{post.category}} </td>
                                        <td>{{post.gambar}}</td>
                                        <td><a href="images/{{post.slug}}" class="bi bi-eye-fill text-info"></a></td>
                                        <td>
                                        {% if post.waktu_update %}
                                            {{ post.waktu_update_indonesia }}
                                        {% else %}
                                            {{ post.waktu_indonesia }}
                                        {% endif %}
                                        </td>
                                        <td >
                                            <a class="bi bi-recycle text-warning " href="{% url 'database:update' post.id %}" role="button"></a>
                                        </td>
                                        <td>
                                            <a class="bi bi-trash3-fill text-danger" href="{% url 'database:delete' post.id %}" role="button"></a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>   
                            {% if Post_Model.has_other_pages %}
                            <nav aria-label="Page navigation example">
                                <ul class="pagination">
                                    {% if Post_Model.has_previous %}
                                        <li class="page-item"><a class="page-link" href="?page={{ Post_Model.previous_page_number }}">&laquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}

                                    {% for i in Post_Model.paginator.page_range %}
                                        {% if Post_Model.number == i %}
                                            <li class="active"><a class="page-link">{{i}}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                        {% endif %}
                                    {% endfor%}

                                    {% if Post_Model.has_next %}
                                        <li class="page-item"><a class="page-link" href="?page={{ Post_Model.next_page_number }}">&raquo;</a></li>
                                    {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>  
                            </nav>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>             
    </div>
</div>
{% endblock base%}

database/templates/database/update.html
{% extends "html_user/base_user.html"%}
{% load static %}
{% load tz %}
{% load widget_tweaks%}

{% block app_css%} 
<link rel="stylesheet" type="text/css" href="{% static "database/css/styless.css" %}">
{% endblock app_css%} 

{% block base%}
<section class="jumbotron jumbotron-fluid text-black text-center" style="margin-top: 3rem; padding-bottom: 0rem;">
    <h1 class="display-4 ">{{ Judul }}</h1>
</section>

<section class="container-fluid glass" style="margin-top: -6rem">
    <h3 class="text-center" style="margin: 2rem;">Update the Database</h3>
        <div class="data-form ">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupSelect01">{% render_field Post_Form.category.label %}</label>
                    {% render_field Post_Form.category class="form-control" id="inputGroupSelect01"%}
                </div>
                <br>
                <div class="input-group mb-3">
                    {% render_field Post_Form.gambar class="form-control" id="inputGroupFile02" type="file"%}
                    <button class="btn btn-outline-secondary" type="submit">Upload</button>
                </div>    
            </form>
        </div>
    </div>
</section>
{% endblock base%}